### ISSUE TITLE
State of tensorflow/bazel/jaxlib/abseil

### ISSUE THREAD

**Issue by xhochy** [conda-forge/tensorflow-feedstock#265]
### Comment:

Hello @h-vetinari , @hmaarrfk and @ngam ,

I have been away for nearly two months and happy to look into getting the stack forward. As there has been several things going and many things currently running in parallel: Can someone give me some hints on what we are currently working and where you would appreciate my involvement the most (now that I have some time for this again)?

Sorry to do this as an issue but we don't seem to have a better space to discuss this.

**Comment by h-vetinari** [comment]
Hey @xhochy, good to have you back. :)

The status AFAIK:
* abseil has new builds that clarify the ABI-dependence on the C++ standard version (and do a rename), see https://github.com/conda-forge/abseil-cpp-feedstock/pull/35
  * even though grpc 1.46-1.48 was successfully rebuilt with that, this has lead to some to transition pain with grpc because we found that grpc has an implicit runtime dependence on abseil (and zlib) where it shouldn't, see https://github.com/conda-forge/grpc-cpp-feedstock/pull/213. @hmaarrfk has a better idea what's necessary to fix this, but it seems we need to fix the _generation_ of the cmake files, rather those files themselves. Some parts of the abseil migration are stuck on that (though workarounds would be possible).
* bazel migration for abseil is ready, but the feedstock team hasn't reacted. I only had a phone last week, and somehow the bot also didn't respond to the usual incantation to add me as a maintainer
* tensorflow/jaxlib updates are better handled by @ngam (though #253 got merged in your absence and 2.10 is in the works)

**Comment by h-vetinari** [comment]
> see https://github.com/conda-forge/grpc-cpp-feedstock/pull/213. @hmaarrfk has a better idea what's necessary to fix this, but it seems we need to fix the _generation_ of the cmake files, rather those files themselves. Some parts of the abseil migration are stuck on that (though workarounds would be possible).

It's worth noting that the "naïve" approach of patching the checked-in CMakeLists.txt only fails on osx, so it's definitely solvable, but I don't know osx well enough to diagnose what's going wrong. If you could help with that that'd be superb.

**Comment by h-vetinari** [comment]
I think we fixed this with #266 - closing. Let us know if you have any more open questions @xhochy!
