### ISSUE TITLE
No python=3.10 + tensorflow-cpu=2.11 + openssl=3 option for Linux64

### ISSUE THREAD

**Issue by akrherz** [conda-forge/tensorflow-feedstock#295]
### Comment:

Thank you for the heroic efforts to push a tensorflow=2.11 build to conda-forge!  I ran into one dependency snag, that I was unsure if it should work or not:

```
$ mamba create -n dev python=3.10 tensorflow-cpu=2.11 openssl=3
Could not solve for environment specs
Encountered problems while solving:
  - package grpcio-1.51.1-py310h5b20944_0 requires openssl >=1.1.1s,<1.1.2a, but none of the providers can be installed

The environment can't be solved, aborting the operation
```

Indeed, I can get a resolved dep with openssl=1 in play
```
$ mamba create -n dev python=3.10 tensorflow-cpu=2.11
  + openssl                        1.1.1s  h0b41bf4_1               conda-forge/linux-64     Cached
  + tensorflow-cpu                 2.11.0  cpu_py310h718b53a_0      conda-forge/linux-64       30kB
```

Thank you!

**Comment by h-vetinari** [comment]
Can you try this in a fresh environment (e.g. only install Python 3.10 and tensorflow first)? Because the respective builds do exist, so it might be some other conflict showing up.

**Comment by akrherz** [comment]
Hi @h-vetinari , it also fails with just tensorflow

```
$ mamba create -n dev python=3.10 tensorflow=2.11 openssl=3
Could not solve for environment specs
Encountered problems while solving:
  - nothing provides __cuda needed by tensorflow-2.11.0-cuda112py310he87a039_0

The environment can't be solved, aborting the operation
```

if I do tensorflow-base, it works

```
$ mamba create -n dev python=3.10 tensorflow-base=2.11
 + openssl                         3.0.7  h0b41bf4_1               conda-forge/linux-64     Cached
 + tensorflow-base                2.11.0  cpu_py310hc9b7e7f_0      conda-forge/linux-64      131MB
```

**Comment by h-vetinari** [comment]
@ngam @hmaarrfk @pkgw 
I think I know what the issue is here: `tensorflow` depends exactly on the `tensorflow-base` output, but does not get a different hash for the different openssl versions. That means we only get _one_ wrapper (either OpenSSL 1 or 3). For osx this wasn't an issue because we _only_ built OpenSSL 3, but for linux it means we have to fix it (e.g. add an OpenSSL host-dep to `tensorflow` while the migration isn't closed yet).

I think the easiest (i.e. without a rebuild) might be to patch out the exact dependence on the hash of `tensorflow-base`, and letting it just depend on the version & build. I'll see if I can get that to work.

**Comment by h-vetinari** [comment]
Took a bit of fiddling to get right, but I think I've got it now: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/381

**Comment by hmaarrfk** [comment]
I've been noticing this today too. I was trying to ensure it wasn't something in my weird environments.

**Comment by hmaarrfk** [comment]
Confirmed that:
```
conda clean -i && mamba install openssl=3 "tensorflow=2.11.0=cuda*"
```
now works.

`conda clean -i` ensures that you get new repository metadata.
