### ISSUE TITLE
Skipping tests on all platforms but windows is not valid

### ISSUE THREAD

**Issue by PhilipMay** [conda-forge/tensorflow-feedstock#63]
Hi.
You skip all tests but on windows. This is not valid cause it breaks the build of every other package that depends on tensorflow on linux and mac.

https://github.com/conda-forge/tensorflow-feedstock/blob/034249e4e9a5a026f4bda812dfadef89ff5199b3/recipe/meta.yaml#L46

**Comment by dhirschfeld** [comment]
How does not running an import test *"break the build"*?

*Edit:* I see what you're getting at - not being able to import the `tensorflow` package on the CI servers breaks CI for all packages which need to import `tensorflow`.

It's not the skipping tests which is the problem but the fact that it doesn't actually work on the CI servers (which is why the tests were skipped). Given that, I'm inclined to close this issue as a dup of #6.

**Comment by PhilipMay** [comment]
Ok...

**Comment by PhilipMay** [comment]
So close it or not?

**Comment by dhirschfeld** [comment]
I don't think it's valid anymore as TF is built from source so I'd close this issue. I can't myself as I'm no longer a maintainer.

**Comment by PhilipMay** [comment]
Closing it.
